GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "bat",
    "name": "batter",
    "password": "11111"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "bat",
    "password": "11111"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhdCIsImlkIjoiNjQ5YThlMzg1OWJiYjQzODI3YTBmYTcxIiwiaWF0IjoxNjg3ODUwNTU2LCJleHAiOjE2ODc4NTQxNTZ9.zQiK8ZA_s3K0trVcO6cciRWWABkn_R38F6rf3hy0k68

{
    "title": "note3",
    "author": "Freshc0w",
    "url": "www.great.com",
    "likes": 1
}














###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "CAT",
    "author": "Freshc0w",
    "url": "www.great.com",
    "likes": 2,
    "userId": "64994ed695bf97f8b5a1966a"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "bat3",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "bat3",
    "password": "salainen"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "bat5",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "bat4",
    "password": "salainen"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhdDMiLCJpZCI6IjY0OWE2NDg5NDU1NTRhZWRiYzRjMDA5MiIsImlhdCI6MTY4NzgzOTkyMywiZXhwIjoxNjg3ODQzNTIzfQ.ZtnjLKRajJHtft6yA6Id4XqoOHEyoi5mWgZeL18TtFg

{
    "title": "CA7T",
    "author": "Freshc0w",
    "url": "www.great.com",
    "likes": 2
}

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhdDQiLCJpZCI6IjY0OWE2ZDE3ZTdkOGI2OWY5ZjIwZGRmYiIsImlhdCI6MTY4Nzg0MjA4NCwiZXhwIjoxNjg3ODQ1Njg0fQ.FFbuBSY9TusNOgBLdMedrCea2ugqy1ajPEH0a3fyhKo

{
    "title": "BA7T",
    "author": "Freshc0w",
    "url": "www.great.com",
    "likes": 2
}

### success delete
DELETE http://localhost:3003/api/blogs/649a752591e711fd8e67ab95
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhdDQiLCJpZCI6IjY0OWE2ZDE3ZTdkOGI2OWY5ZjIwZGRmYiIsImlhdCI6MTY4Nzg0MjA4NCwiZXhwIjoxNjg3ODQ1Njg0fQ.FFbuBSY9TusNOgBLdMedrCea2ugqy1ajPEH0a3fyhKo

### not a success delete
DELETE http://localhost:3003/api/blogs/649a69c7851dc8ee2a1df082
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhdDQiLCJpZCI6IjY0OWE2ZDE3ZTdkOGI2OWY5ZjIwZGRmYiIsImlhdCI6MTY4Nzg0MjA4NCwiZXhwIjoxNjg3ODQ1Njg0fQ.FFbuBSY9TusNOgBLdMedrCea2ugqy1ajPEH0a3fyhKo