GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "CAT",
    "author": "Freshc0w",
    "url": "www.great.com",
    "likes": 2
}